# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose_interaction.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pose_interaction.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16pose_interaction.proto\"\x0e\n\x0c\x45mptyMessage\"\x1e\n\x0cRefIDMessage\x12\x0e\n\x06ref_id\x18\x01 \x01(\t\"\'\n\x07Heading\x12\x0e\n\x06ref_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"%\n\x05\x46rame\x12\x0e\n\x06ref_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x32\xbb\x01\n\x0fPoseInteraction\x12+\n\x10SendHeadingBytes\x12\x08.Heading\x1a\r.EmptyMessage\x12*\n\x0fGetHeadingBytes\x12\r.RefIDMessage\x1a\x08.Heading\x12\'\n\x0eSendFrameBytes\x12\x06.Frame\x1a\r.EmptyMessage\x12&\n\rGetFrameBytes\x12\r.RefIDMessage\x1a\x06.Frameb\x06proto3'
)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=40,
)


_REFIDMESSAGE = _descriptor.Descriptor(
  name='RefIDMessage',
  full_name='RefIDMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_id', full_name='RefIDMessage.ref_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=72,
)


_HEADING = _descriptor.Descriptor(
  name='Heading',
  full_name='Heading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_id', full_name='Heading.ref_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Heading.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=113,
)


_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ref_id', full_name='Frame.ref_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='Frame.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['RefIDMessage'] = _REFIDMESSAGE
DESCRIPTOR.message_types_by_name['Heading'] = _HEADING
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYMESSAGE,
  '__module__' : 'pose_interaction_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  })
_sym_db.RegisterMessage(EmptyMessage)

RefIDMessage = _reflection.GeneratedProtocolMessageType('RefIDMessage', (_message.Message,), {
  'DESCRIPTOR' : _REFIDMESSAGE,
  '__module__' : 'pose_interaction_pb2'
  # @@protoc_insertion_point(class_scope:RefIDMessage)
  })
_sym_db.RegisterMessage(RefIDMessage)

Heading = _reflection.GeneratedProtocolMessageType('Heading', (_message.Message,), {
  'DESCRIPTOR' : _HEADING,
  '__module__' : 'pose_interaction_pb2'
  # @@protoc_insertion_point(class_scope:Heading)
  })
_sym_db.RegisterMessage(Heading)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), {
  'DESCRIPTOR' : _FRAME,
  '__module__' : 'pose_interaction_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  })
_sym_db.RegisterMessage(Frame)



_POSEINTERACTION = _descriptor.ServiceDescriptor(
  name='PoseInteraction',
  full_name='PoseInteraction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=155,
  serialized_end=342,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendHeadingBytes',
    full_name='PoseInteraction.SendHeadingBytes',
    index=0,
    containing_service=None,
    input_type=_HEADING,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetHeadingBytes',
    full_name='PoseInteraction.GetHeadingBytes',
    index=1,
    containing_service=None,
    input_type=_REFIDMESSAGE,
    output_type=_HEADING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendFrameBytes',
    full_name='PoseInteraction.SendFrameBytes',
    index=2,
    containing_service=None,
    input_type=_FRAME,
    output_type=_EMPTYMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFrameBytes',
    full_name='PoseInteraction.GetFrameBytes',
    index=3,
    containing_service=None,
    input_type=_REFIDMESSAGE,
    output_type=_FRAME,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_POSEINTERACTION)

DESCRIPTOR.services_by_name['PoseInteraction'] = _POSEINTERACTION

# @@protoc_insertion_point(module_scope)
